# Rockchip sample Makefile

all:
	@$(SAMPLE_CC) $(SAMPLE_CFLAGS) sample_camera_stresstest.c -o sample_camera_stresstest $(LD_FLAGS)

install:
	@mv -f sample_camera_stresstest $(SAMPLE_OUT_DIR)/bin

clean:
	@echo "clean test"
